בקשה 1
NetFree-Community/netfree-anywhere pull request #7
Opened 2018-12-28 10:43 UTC by Men770

התחברות אוטומטית

2018-12-28 11:08 UTC, magicode commented on nfaTray/MainWindow.xaml.cs
> +                proto = match.Groups["proto"].Value == "tcp" ? ProtocolType.Tcp : (match.Groups["proto"].Value == "udp" ? ProtocolType.Udp : ProtocolType.Unspecified) ;
זה קוד שובר
ProtocolType.Unspecified

יש למטה if על  ProtocolType.Unknown

2018-12-28 11:11 UTC, Men770 commented on nfaTray/MainWindow.xaml.cs
> +                proto = match.Groups["proto"].Value == "tcp" ? ProtocolType.Tcp : (match.Groups["proto"].Value == "udp" ? ProtocolType.Udp : ProtocolType.Unspecified) ;
תודה

2018-12-28 11:59 UTC, Men770 commented
@magicode 
שיופיע האפשרות להתחבר לשרתי usa וuk
ראיתי בקוד שהשרתים מגיעים משרת שלך.

העלתי את הבקשה השנייה

2018-12-29 16:58 UTC, magicode commented
צריך לבודד כל נושא בנפרד.

2018-12-29 17:49 UTC, magicode requested changes

2018-12-29 17:49 UTC, magicode commented on nfaService/oVpnConnetion.cs
> +                Process.Start("rasdial.exe", ip + port + " " + user + " " + pass + " ");
זה התחברות דרך PPTP ?
אם כן איך יהיה הניתוק?

2018-12-29 17:52 UTC, Men770 commented on nfaService/oVpnConnetion.cs
> +                Process.Start("rasdial.exe", ip + port + " " + user + " " + pass + " ");
זה משהו שניסיתי ל pptp והפסקתי באמצע כי השארתי באמצע כי הקטע הזה הוא פשוט מה שראיתי למרות שלא חיפשתי על זה ורציתי לשמור ובטעות הכנסתי לקוד.

2018-12-29 18:11 UTC, closed without merging